# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Sanise SOYLU
# Description of the Site
description: Portfolio BTS SIO
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: sso@mtb111
linkedin_username: Sanise Soylu
github_username:  Sanise

# Google Analytics
google-analytics: UA-163806439-1

# Name of the Author
author-name: Sanise Soylu
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: Je suis Sanise SOYLU, étudiante en alternance en BTS Services informatiques aux organisations (SIO) option Solutions logicielles et applications métiers (SLAM). L'entreprise dans lequel je travail est MTB 111. Je suis issu d'un baccalaurérat technologique Sciences et Technologies de l'Industrie et du Développement Durable (STI2D) option systèmes d'information et numérique (SIN) en 2022. Ensuite j'ai étudié 1 semestre en classe préparatoire Ingénieur au CESI.  ICI ¨RESENTATION DE MTB 111


# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
